online_shop/main/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from main import models
from . import views


app_name='main'

urlpatterns = [
    path('',TemplateView.as_view(template_name='main/home.html'),name='home'),
    path('about-us/',TemplateView.as_view(template_name='main/about_us.html'),name='about_us'),
    path('contact-us/',views.ContactPageView.as_view(),name='contact_us'),
    path('productos/<slug:tag>/',views.ProductoListView.as_view(),name='productos'),
    path("producto/<slug:slug>/",DetailView.as_view(model=models.Producto),name="producto",),
    path('signup/', views.Signup_view.as_view(), name="signup"),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/', views.Logout_view.as_view(), name="logout"),
    path('direccion/',views.DireccionListView.as_view(),name='direcciones_list'),
    path('direccion/<int:pk>/',views.DireccionUptadeView.as_view(),name='direccion_update'),
    path('direccion/<int:pk>/delelete/',views.DeleteDireccion.as_view(),name='confirm_delete'),
    path('direccion/create/',views.DireccionCreateView.as_view(),name='direccion_create'),
    path('add_to_basket/',views.add_to_basket,name='add_to_basket'),
    path('basket/',views.manage_basket,name='basket')

]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/main/models.py
from django.db import models

from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)

from django.core.validators import MinValueValidator

class ProductoTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)

class ProductoTag(models.Model):
    nombre = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    descripcion =  models.TextField('Descripción',blank=True)
    activo = models.BooleanField(default=True)
    objects = ProductoTagManager()

    class Meta:
        verbose_name_plural=('Tag de Productos')

    def __str__(self):
        return self.nombre

    def natural_key(self):
        return (self.slug,)


class ProductosActivos(models.Manager):
    def activo(self):
        return self.filter(activo=True)

class Producto(models.Model):
    nombre = models.CharField('Nombre',max_length=60)
    tags = models.ManyToManyField('ProductoTag', blank=True)
    descripcion =  models.TextField('Descripción',blank=True)
    precio = models.DecimalField('Precio',max_digits=6,decimal_places=2)
    slug = models.SlugField(max_length=48)
    activo = models.BooleanField(default=True)
    en_stock = models.BooleanField(default=True)
    actualizacion = models.DateTimeField('Ultima Actualización',auto_now=True)
    #objects = ProductosActivos()


    class Meta:
        verbose_name_plural=('Productos')

    def __str__(self):
        return self.nombre


class ProductoImagen(models.Model):
    producto = models.ForeignKey(
                Producto,
                on_delete= models.CASCADE,
                related_name="imagenes")

    imagen = models.ImageField(upload_to='imagenes-del-producto')
    thumbnail =  models.ImageField(upload_to='producto-thumbnails',null=True,blank=True)

    class Meta:
        verbose_name = ('Imagen de Producto')
        verbose_name_plural=('Imagenes de Productos')


#User model configuration
class UserManager(BaseUserManager):

    def create_user(self,email,password=None):
        if not email:
            raise ValueError('El correo electrónico no puede dejarse en blanco.')

        email= self.normalize_email(email)
        user = self.model(email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password):
        user = self.create_user(
                    email=email,
                    password=password)

        user.is_staff = True
        user.is_admin = True
        user.is_superuser= True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser,PermissionsMixin):
        email   =  models.EmailField(max_length=60,unique=True)
        nombre = models.CharField(max_length=100,blank=True)
        apellido = models.CharField(max_length=100,blank=True)


        USERNAME_FIELD  = 'email'
        REQUIRED_FIELDS = []

        objects = UserManager()

        date_joined  =  models.DateTimeField(verbose_name="Fecha de ingreso",auto_now_add=True)
        last_login   =  models.DateTimeField(verbose_name="Ultima fecha de Sesión",auto_now=True)
        is_admin     =  models.BooleanField(verbose_name="¿Es Administrador?",default=False)
        is_active    =  models.BooleanField(verbose_name="¿Esta Acivo?",default=True)
        is_staff     =  models.BooleanField(verbose_name="¿Es parte del Staff?",default=False)
        is_superuser =  models.BooleanField(verbose_name="¿Es Super Usuario?",default=False)

        def  __str__(self):
            return f'{self.nombre}'

        def has_perm(self,perm,obj=None):
            return self.is_admin


        def has_module_perms(self,app_label):
            return True

class Direccion(models.Model):

    PAISES_SOPORTADOS = (
       ('mx','Mexico'),
       ('eu','EUA')
    )

    usuario = models.ForeignKey('Usuario',related_name="direcciones",on_delete=models.CASCADE)
    nombre = models.CharField(max_length=60)
    direccion1 = models.CharField('Dirección Linea 1',max_length=60)
    direccion2 = models.CharField('Dirección Linea 2',max_length=60,blank=True)
    codigo_postal = models.CharField('ZIP / Código Postal',max_length=12)
    ciudad = models.CharField(max_length=60)
    pais = models.CharField(max_length=3,choices=PAISES_SOPORTADOS)

    class Meta:
        verbose_name_plural = ('Direcciones')

    def __str__(self):
        return  ",".join(
        [     self.nombre,
              self.direccion1,
              self.direccion2,
              self.codigo_postal,
              self.ciudad,
              self.pais,
          ])


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, 'Open'),(SUBMITTED,'Submitted'))
    usuario = models.ForeignKey(Usuario,on_delete= models.CASCADE, related_name="baskets",blank=True,null=True)
    status =  models.IntegerField(choices=STATUSES, default=OPEN)

    def  is_empty(self):
        return self.baskets_lines.all().count() == 0

    def count(self):
        return sum(basket_line.cantidad for basket_line in self.baskets_lines.all())



class BasketLine(models.Model):
    basket = models.ForeignKey(Basket,on_delete=models.CASCADE,related_name ="baskets_lines")
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE,related_name="productos")
    cantidad = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])

online_shop/main/forms.py
from django import forms
from django.core.mail  import  send_mail
import logging
from django.contrib.auth.forms import (UserCreationForm,UsernameField)
from django.contrib.auth import (get_user_model, authenticate)
from . import models
logger = logging.getLogger(__name__)
from  django.forms import inlineformset_factory


class ContactForm(forms.Form):
    nombre = forms.CharField(label='Nombre',max_length=100)
    email =  forms.EmailField(label="Email")
    mensaje = forms.CharField(label='Mensaje',max_length=600,widget=forms.Textarea)


    def send_mail(self):
        logger.info('Enviando email hacia  mi servicio custumer')
        mensaje = 'De: {0}\n Email:{1}\n mensaje:{2}'.format(
            self.cleaned_data['nombre'],
            self.cleaned_data['email'],
            self.cleaned_data['mensaje'],
        )

        send_mail(
            'Mensaje del Sitio',
            mensaje,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )

class LoginAutentificationForm(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self,request=None,*args,**kwargs):
        self.request = request
        self.user =None
        super(LoginAutentificationForm,self).__init__(*args,**kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if email is not None and password:
            self.user = authenticate(email=email,password=password)
        if self.user is None:
            raise forms.ValidationError('error de autentificación')
        logger.info("Autentificación éxitosa=%s",email)
        return self.cleaned_data
    def get_user(self):
        return self.user


class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields=('email','password1', 'password2')


    def send_email(self):
        logger.info("envio un email al usuario que se registro",
        self.cleaned_data["email"])
        mensaje = "{Bienvenido { self.cleaned_data['email']}"

        send_mail(
            "Bienvenido a nuestra tienda en linea",
            mensaje,
            "site@booktime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True)



class UpdateViewForm(forms.ModelForm):
    PAISES_SOPORTADOS = (
             ('mx','Mexico'),
             ('eu','EUA')
        )

    pais = forms.ChoiceField(choices=PAISES_SOPORTADOS,widget=forms.Select(attrs={'class':'form-control'}))

    class Meta:
        model = models.Direccion
        fields=('nombre','direccion1', 'direccion2','codigo_postal','ciudad','pais')


BasketLineFormSet = inlineformset_factory(
        models.Basket,
        models.BasketLine,
        fields = ('cantidad',),
        extra=0,)

online_shop/main/views.py
from django.views.generic import   (ListView,RedirectView)
from django.views.generic.edit import (FormView,CreateView,UpdateView,DeleteView,)

from django.shortcuts import render,get_object_or_404,redirect
from main import models
from main.forms import (ContactForm,SignUpForm,LoginAutentificationForm,UpdateViewForm,BasketLineFormSet)
import logging
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
logger = logging.getLogger(__name__)
from django.http import  HttpResponseRedirect
from django.urls import  reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ContactPageView(FormView):
    template_name= 'main/contact_form.html'
    form_class = ContactForm
    success_url = '/'

    def form_valid(self,form):
        form.send_mail()
        return super(ContactPageView, self).form_valid(form)


class ProductoListView(ListView):
    template_name = "main/producto_list.html"
    model= models.Producto
    paginate_by= 4

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['tag'] = self.kwargs['tag']
        return data

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        queryset = super().get_queryset()

        if tag != 'all':
            self.tag = get_object_or_404(models.ProductoTag,slug=tag)

            if self.tag:
                productos = queryset.filter(activo=True).filter(tags=self.tag)

        else:
            productos = queryset.filter(activo=True)
        return productos.order_by('nombre')



class Logout_view(RedirectView):
    pattern_name = 'main:home'

    def get(self,request,*args,**kwargs):
        logout(request)
        return super(Logout_view,self).get(request,*args,**kwargs)


class Signup_view(FormView):
    template_name = "main/signup.html"
    form_class = SignUpForm

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect("/")
        else:
            return super(Signup_view,self).dispatch(request,*args,**kwargs)

    def get_success_url(self):
        return self.request.GET.get("next", "/")


    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info(
            "New signup for email=%s through SignupView", email
        )
        user = authenticate(email=email, password=raw_password)
        login(self.request, user)
        form.send_email()
        messages.info(
            self.request, "Haz creado una cuenta de manera exitosa"
        )
        return response

class LoginView(FormView):
    form_class = LoginAutentificationForm
    template_name = "main/login.html"
    success_url =  '/'

    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect("/")
        else:
            return super(LoginView,self).dispatch(request,*args,**kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        messages.info(
                self.request, "login exitoso"
        )
        return super(LoginView, self).form_valid(form)

class DireccionListView(LoginRequiredMixin,ListView):
    model = models.Direccion
    template_name = "main/direccion_list.html"
    context_object_name = 'direcciones'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(usuario=self.request.user)


class DireccionUptadeView(LoginRequiredMixin,UpdateView):
    template_name = "main/direccion_update.html"
    model= models.Direccion
    form_class = UpdateViewForm

    success_url = reverse_lazy("main:direcciones_list")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(usuario=self.request.user)


class DeleteDireccion(LoginRequiredMixin,DeleteView):
     template_name = "main/confirm_delete.html"
     model = models.Direccion
     success_url = reverse_lazy("main:direcciones_list")

     def  get_queryset(self):
         queryset = super().get_queryset()
         return queryset.filter(usuario=self.request.user)


class DireccionCreateView(LoginRequiredMixin,CreateView):
    template_name = "main/direccion_create.html"
    model = models.Direccion
    form_class = UpdateViewForm
    success_url = reverse_lazy("main:direcciones_list")


    def form_valid(self,form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        obj.save()
        messages.success(self.request,"nueva Dirección creada")
        return super().form_valid(form)


def add_to_basket(request):
    producto = get_object_or_404(models.Producto,pk=request.GET.get('producto_id'))
    basket =  request.basket
    if not  basket:
        if request.user.is_authenticated:
            usuario = request.user
        else:
            usuario = None
        basket = models.Basket.objects.create(usuario=usuario)
        request.session['basket_id'] = basket.id
    basket_line ,created = models.BasketLine.objects.get_or_create(basket=basket,producto=producto)

    if not created:
        basket_line.cantidad +=1
        basket_line.save()
    return HttpResponseRedirect(reverse('main:producto',args=(producto.slug,)))


def  manage_basket(request):
    if not request.basket:
        return render(request,'main/basket.html',{ 'formset': None})
    if request.method == 'POST':
        formset = BasketLineFormSet(request.POST,instance=request.basket)
        if formset.is_valid():
            formset.save()
    else:
        formset = BasketLineFormSet(instance=request.basket)
    if request.basket.is_empty():
        return render(request,'main/basket.html',{ 'formset': None})

    return render(request,'main/basket.html',{ 'formset': formset})

online_shop/main/templates/main/about_us.html
{% extends "base.html" %}

{% block content  %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>

{% endblock%}

online_shop/main/templates/main/confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    <p>Estas seguro de eliminar la direccion de nombre: {{ object.nombre }}?</p>
    <button type="submit"  class="btn btn-primary"  name="button">Si,Borrar</button>
</form>

{% endblock %}

online_shop/main/templates/main/contact_form.html
{% extends "base.html" %}

{% block content %}

  <h2>Contact us</h2>
    <p>Please fill the form below to contact us</p>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        {{ form.nombre.label_tag }}
        <input
            class ='form-control {% if form.nombre.errors %} is-invalid {% endif %}'
            type="text"
            id='id_nombre'
            name="nombre"
            value="{{ form.nombre.value|default:'' }}">
        {% if form.nombre.errors %}
            <div class="invalid-feedback">
              {{ form.nombre.errors}}
            </div>
        {%endif%}
      </div>
      <div class="form-group">
        {{ form.email.label_tag }}
        <input
        class ='form-control {% if form.email.errors %} is-invalid {% endif %}'
        type="email"
        id="id_email"
        name="email"
        value="{{ form.email.value|default:'' }}">
        {% if form.email.errors %}
            <div class="invalid-feedback">
              {{ form.email.errors}}
            </div>
        {%endif%}
      </div>
      <div class="form-group">
          {{ form.mensaje.label_tag }}
          <textarea
              class='form-control {% if form.mensaje.errors %} is-invalid {% endif %}'
              id='id_mensaje'
              name="mensaje"
              rows="3">{{form.mensaje.value|default:''}}</textarea>
          {% if form.mensaje.errors %}
            <div class="invalid-feedback">
              {{ form.mensaje.errors}}
            </div>
          {%endif%}
      </div>

      <button type="submit" class="btn btn-primary">Enviar</button>
    </form>


{% endblock %}

online_shop/main/templates/main/direccion_create.html
{% extends "base.html" %}
{% block  content %}
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="form-group">
      {{ form.nombre.label_tag}}
       <input
          class ='form-control {% if form.nombre.errors %} is-invalid {% endif %}'
          type="text"
          name="nombre"
         id='id_nombre'
          value="{{ form.nombre.value|default:''}}">
        {% if form.nombre.errors %}
        <div class="invalid-feedback">
                {{ form.nombre.errors}}
        </div>
        {%endif%}

    </div>
    <div class="form-group">
      {{ form.direccion1.label_tag}}
       <input
          class ='form-control {% if form.direccion1.errors %} is-invalid {% endif %}'
          type="text"
          name="direccion1"
         id='id_direccion1'
          value="{{ form.direccion1.value|default:''}}">

    </div>
    {% if form.direccion1.errors %}
        <div class="invalid-feedback">
          {{ form.direccion1.errors}}
        </div>
    {%endif%}
    <div class="form-group">
      {{ form.direccion2.label_tag}}
       <input
          class ='form-control {% if form.direccion2.errors %} is-invalid {% endif %}'
          type="text"
          name="direccion2"
         id='id_direccion2'
          value="{{ form.direccion2.value|default:''}}">

    </div>
    <div class="form-group">
      {{ form.codigo_postal.label_tag}}
       <input
          class ='form-control {% if form.codigo_postal.errors %} is-invalid {% endif %}'
          type="text"
          name="codigo_postal"
         id='id_codigo_postal'
          value="{{ form.codigo_postal.value|default:''}}">
          {% if form.codigo_postal.errors %}
              <div class="invalid-feedback">
                {{ form.codigo_postal.errors}}
              </div>
          {%endif%}
    </div>

    <div class="form-group">
      {{ form.ciudad.label_tag}}
       <input
          class ='form-control {% if form.ciudad.errors %} is-invalid {% endif %}'
          type="text"
          name="ciudad"
         id='id_ciudad'
          value="{{ form.ciudad.value|default:''}}">
      {% if form.ciudad.errors %}
      <div class="invalid-feedback">
        {{ form.ciudad.errors}}
      </div>
      {%endif%}
    </div>
      {{ form.pais.label_tag}}
      {{ form.pais}}
    <button type="submit" class="btn btn-primary mt-3">Crear Direccion</button>
  </form>



{% endblock %}

online_shop/main/templates/main/direccion_list.html
{% extends "base.html" %}



{% block  content %}
<h4> Lista de  tus direcciones</h4>
<p>
  <span class="badge badge-primary badge-pill">
      <a  style="color: white; font-size: 15px;"href="{% url 'main:direccion_create' %}">Agregar Dirección</a>
  </span>
</p>
{% for direccion in  direcciones %}
<ul class="list-group pb-4">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ direccion.nombre}}

  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ direccion.direccion1}}

  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ direccion.direccion2}}

  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ direccion.ciudad}}
  </li>
  {% if direccion.pais == 'mx' %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    México
  </li>
  {% elif direccion.pais == 'eu' %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
   EUA
  </li>
  {%else%}
  <li class="list-group-item d-flex justify-content-between align-items-center">
   no select
  </li>
  {% endif %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <span class="badge badge-primary badge-pill">
      <a  style="color: white; font-size: 15px;"href="{% url 'main:direccion_update' pk=direccion.id %}">Update</a>

    </span>
    <span class="badge badge-primary badge-pill">
      <a  style="color:white; font-size: 15px;"href="{% url 'main:confirm_delete' pk=direccion.id %}">Delete</a>
    </span>
  </li>




</ul>
{% endfor %}

{% endblock %}

online_shop/main/templates/main/direccion_update.html
{% extends "base.html" %}
{% block  content %}
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="form-group">
      {{ form.nombre.label_tag}}
       <input
          class ='form-control {% if form.nombre.errors %} is-invalid {% endif %}'
          type="text"
          name="nombre"
         id='id_nombre'
          value="{{ form.nombre.value|default:''}}">
        {% if form.nombre.errors %}
        <div class="invalid-feedback">
                {{ form.nombre.errors}}
        </div>
        {%endif%}

    </div>
    <div class="form-group">
      {{ form.direccion1.label_tag}}
       <input
          class ='form-control {% if form.direccion1.errors %} is-invalid {% endif %}'
          type="text"
          name="direccion1"
         id='id_direccion1'
          value="{{ form.direccion1.value|default:''}}">

    </div>
    {% if form.direccion1.errors %}
        <div class="invalid-feedback">
          {{ form.direccion1.errors}}
        </div>
    {%endif%}
    <div class="form-group">
      {{ form.direccion2.label_tag}}
       <input
          class ='form-control {% if form.direccion2.errors %} is-invalid {% endif %}'
          type="text"
          name="direccion2"
         id='id_direccion2'
          value="{{ form.direccion2.value|default:''}}">

    </div>
    <div class="form-group">
      {{ form.codigo_postal.label_tag}}
       <input
          class ='form-control {% if form.codigo_postal.errors %} is-invalid {% endif %}'
          type="text"
          name="codigo_postal"
         id='id_codigo_postal'
          value="{{ form.codigo_postal.value|default:''}}">
          {% if form.codigo_postal.errors %}
              <div class="invalid-feedback">
                {{ form.codigo_postal.errors}}
              </div>
          {%endif%}
    </div>

    <div class="form-group">
      {{ form.ciudad.label_tag}}
       <input
          class ='form-control {% if form.ciudad.errors %} is-invalid {% endif %}'
          type="text"
          name="ciudad"
         id='id_ciudad'
          value="{{ form.ciudad.value|default:''}}">
      {% if form.ciudad.errors %}
      <div class="invalid-feedback">
        {{ form.ciudad.errors}}
      </div>
      {%endif%}
    </div>
      {{ form.pais.label_tag}}
      {{ form.pais}}
    <button type="submit" class="btn btn-primary mt-3">Guardar cambios</button>
  </form>




{% endblock %}

online_shop/main/templates/main/login.html
{% extends "base.html" %}
{% block content %}
<h2>Login</h2>
<p>Introduce tu datos por favor</p>
<form method="post" novalidate>
    {% csrf_token %}
    <div class="form-group">
        {{ form.email.label_tag}}
    <input
        class ='form-control {% if form.email.errors %} is-invalid {% endif %}'
        type="text"
        name="email"
        id='id_email'
        value="{{ form.email.value|default:''}}">
      {% if form.email.errors %}
          <div class="invalid-feedback">
            {{ form.email.errors}}
          </div>
      {%endif%}
    </div>
    <div class="form-group">
      {{ form.password.label_tag}}
      <input
        class ='form-control {% if form.password.errors %} is-invalid {% endif %}'
        type="password"
        name="password"
        id='id_password'
        value="{{ form.password.value|default:''}}">
        {% if form.password.errors %}
            <div class="invalid-feedback">
              {{ form.password.errors }}
            </div>
        {%endif%}
      </div>
      {% if form.non_field_errors %}
          {% for error in form.non_field_errors%}
                  <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                  </div>
          {% endfor%}
      {%endif%}
     <button type="submit" class="btn btn-success">Login</button>
  </form>

{% endblock content %}

online_shop/main/templates/main/producto_detail.html
{% extends "base.html" %}
{% block tag_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<style>

*{
  margin: 0;
  padding: 0;
  font-family: "montserrat",sans-serif;
  box-sizing: border-box;
}

.gallery-section{
  width: 100%;
  padding: 60px 0;
  background: #f1f1f1;
}

.inner-width{
  width: 100%;
  max-width: 1200px;
  margin: auto;
  padding: 0 20px;
}

.gallery-section h1{
  text-align: center;
  text-transform: uppercase;
  color: #333;
}

.border{
  width: 180px;
  height: 4px;
  background: #333;
  margin: 60px auto;
}

.gallery-section .gallery{
  display: flex;
  flex-wrap: wrap-reverse;
  justify-content: center;
}

.gallery-section .image{
  flex: 25%;
  overflow: hidden;
  cursor: pointer;
}

.gallery-section .image img{
  width: 100%;
  height: 100%;
  transition: 0.4s;
}

.gallery-section .image:hover img{
  transform: scale(1.4) rotate(15deg);
}

@media screen and (max-width:960px) {
  .gallery-section .image{
    flex: 33.33%;
  }
}

@media screen and (max-width:768px) {
  .gallery-section .image{
    flex: 50%;
  }
}

@media screen and (max-width:480px) {
  .gallery-section .image{
    flex: 100%;
  }
}


</style>
{% endblock%}
{% block content %}
<div style="position: relative; width: 100%; height: 50px;padding-top:20px;">
   <button  style="position:absolute; right:0;" type="button" class="btn btn-secondary">
     <a href="{% url 'main:add_to_basket' %}?producto_id={{ object.id }}">Añadir a Canasta</a>
   </button>
</div>

  <h1 style="padding-top:20px;">Producto</h1>
  <table class="table">
    <tr>
      <th>Nombre</th>
      <td>{{ object.nombre }}</td>
    </tr>
    <tr>
      <th>Precio</th>
      <td>{{ object.precio }}</td>
    </tr>
    <tr>
      <th>Descripcion</th>
      <td>{{ object.descripcion|linebreaks }}</td>
    </tr>
    <tr>
      <th>Tags</th>
    <td>{{ object.tags.all|join:","|default:"No tags  disponibles" }}</td>
    </tr>
    <tr>
     <th>En stock</th>
     <td>{{ object.en_stock|yesno|capfirst }}</td>
   </tr>
   <tr>
     <th>Ultima Actualizacion</th>
     <td>{{ object.actualizacion|date:"F Y" }}</td>
   </tr>
 </table>

  <h1 style="padding-top:20px;">Imagenes</h1>
<div class="gallery-section">
    <div class="inner-width">
      <div class="gallery">
        {% for imagen in object.imagenes.all %}
          <a href="{{ imagen.imagen.url }}" class="image">
            <img src="{{ imagen.thumbnail.url }}" alt="">
          </a>
        {% endfor%}
      </div>
    </div>
  </div>

 <a href="#">Añadir a la Canasta</a>
<script type="text/javascript">

$(".gallery").magnificPopup({
      delegate: 'a',
      type: 'image',
      gallery:{
        enabled: true
      }
});

</script>
{% endblock content %}