online_shop/main/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from main import models
from . import views


app_name='main'

urlpatterns = [
    path('',TemplateView.as_view(template_name='main/home.html'),name='home'),
    path('about-us/',TemplateView.as_view(template_name='main/about_us.html'),name='about_us'),
    path('contact-us/',views.ContactPageView.as_view(),name='contact_us'),
    path('productos/<slug:tag>/',views.ProductoListView.as_view(),name='productos'),
    path("producto/<slug:slug>/",DetailView.as_view(model=models.Producto),name="producto",),
    path('signup/', views.Signup_view.as_view(), name="signup"),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/', views.Logout_view.as_view(), name="logout"),
    path('direccion/',views.DireccionListView.as_view(),name='direcciones_list'),
    path('direccion/<int:pk>/',views.DireccionUptadeView.as_view(),name='direccion_update'),
    path('direccion/<int:pk>/delelete/',views.DeleteDireccion.as_view(),name='confirm_delete'),
    path('direccion/create/',views.DireccionCreateView.as_view(),name='direccion_create'),
    path('add_to_basket/',views.add_to_basket,name='add_to_basket'),
    path('basket/',views.manage_basket,name='basket')

]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/templates/base.html
{% load static  %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-­fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    {% block tag_css %}
    {% endblock %}
  </head>
            <ul class="nav navbar-nav navbar-right" style="text-align: right">
            </ul>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-­light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button
        class="navbar-toggler"
      type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse"
          id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == '/'%}active{%endif%}">
              <a class="nav-link"
               href="/">Home</a>
            </li>

            <li
              class="nav-item {% if request.path == '/about-us/'%}active{%endif%}">
              <a class="nav-link" href="/about-us/">About us</a>
            </li>
            <li
              class="nav-item {% if request.path == '/contact-us/'%}active{%endif%}">
              <a class="nav-link" href="/contact-us/">Contact us</a>
            </li>
            <li class="nav-item">
              {% if request.basket %}
              <div style="padding-left: 6px;">
                <div style="position:relative;">
                  <a  href="{% url 'main:basket' %}" style="font-size: 28px;"><i class="fa fa-shopping-cart"></i>
                  <div style="width: 22px;height: 22px;font-size:14px;position: absolute;top:50%;right:-15px;
                  color: #666;text-align: center;border-radius:50%; background-color: blue;">{{ request.basket.count }} </div>
                </div>
              </div>
              {%else %}
              <div style="padding-left:6px;">
                <div style="position:relative;">
                  <a href="{% url 'main:basket' %}" style="font-size: 28px"><i class="fa fa-shopping-cart"></i>
                  <div style="width: 22px;height: 22px;font-size:14px;position: absolute;top:50%;right:-15px;
                  color: #666;text-align: center;border-radius:50%;background-color: blue;">0</div>
                </div>
              </div>
              </a>
              {% endif %}
            </li>

          </ul>

        <ul class="nav navbar-nav navbar-right" style="text-align: right">

           {% if request.user.is_authenticated %}
           <li class="nav-item">
             <a href="#" class="nav-link" >  {{ request.user.nombre}}</a>
            </li>
           <li
             class="nav-item {% if request.path == '/logout/'%}active{%endif%}">
             <a class="nav-link" href="/logout/">Logout</a>
           </li>
           {% else %}
          <li
            class="nav-item {% if request.path == '/login/'%}active{%endif%}">
            <a class="nav-link" href="/login/">Login</a>
          </li>
          <li
            class="nav-item {% if request.path == '/signup/'%}active{%endif%}">
            <a class="nav-link" href="/signup/">Registro</a>
          </li>
          {% endif%}
        </ul>

      </div>

  </nav>
  {% for message in messages %}
  <div id="msg"class="alert alert-{{message.tags}}">
    {{ message }}
  </div>
  {% endfor %}
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>

  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript">

  setTimeout(
  function(){
    if($('#msg').length > 0){
      $('#msg').remove()
    }
  },3000)
 AOS.init({
 	duration: 800,
 	easing: 'slide'
 });

  </script>

 </body>
</html>